// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUO.EntityFramework.Core.Repositor.Demo.Context;

namespace SUO.EntityFramework.Core.Repositor.Demo.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SUO.EntityFramework.Core.Repositor.Demo.Model.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserInfoDetailedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoDetailedId");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("SUO.EntityFramework.Core.Repositor.Demo.Model.UserInfoDetailed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInfoDetailed");
                });

            modelBuilder.Entity("SUO.EntityFramework.Core.Repositor.Demo.Model.UserInfo", b =>
                {
                    b.HasOne("SUO.EntityFramework.Core.Repositor.Demo.Model.UserInfoDetailed", "UserInfoDetailed")
                        .WithMany()
                        .HasForeignKey("UserInfoDetailedId");

                    b.Navigation("UserInfoDetailed");
                });
#pragma warning restore 612, 618
        }
    }
}
